services:
  github-profile-stats:
    container_name: github_profile_stats
    build:
      context: .
      dockerfile: dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - '3000:3000'
