services:
  github-profile-stats:
    container_name: github_profile_stats
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '3000:3000'
